# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x0buserservice\"/\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"0\n\x11\x43reateUserRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\"5\n\x12\x43reateUserResponse\x12\x1f\n\x04user\x18\x01 \x01(\x0b\x32\x11.userservice.User\"\x1c\n\x0eGetUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x0fGetUserResponse\x12\x1f\n\x04user\x18\x01 \x01(\x0b\x32\x11.userservice.User\"\x12\n\x10ListUsersRequest\"5\n\x11ListUsersResponse\x12 \n\x05users\x18\x01 \x03(\x0b\x32\x11.userservice.User\"\x1f\n\x11\x44\x65leteUserRequest\x12\n\n\x02id\x18\x01 \x01(\t\"%\n\x12\x44\x65leteUserResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xbd\x02\n\x0bUserService\x12M\n\nCreateUser\x12\x1e.userservice.CreateUserRequest\x1a\x1f.userservice.CreateUserResponse\x12\x44\n\x07GetUser\x12\x1b.userservice.GetUserRequest\x1a\x1c.userservice.GetUserResponse\x12J\n\tListUsers\x12\x1d.userservice.ListUsersRequest\x1a\x1e.userservice.ListUsersResponse\x12M\n\nDeleteUser\x12\x1e.userservice.DeleteUserRequest\x1a\x1f.userservice.DeleteUserResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USER']._serialized_start=30
  _globals['_USER']._serialized_end=77
  _globals['_CREATEUSERREQUEST']._serialized_start=79
  _globals['_CREATEUSERREQUEST']._serialized_end=127
  _globals['_CREATEUSERRESPONSE']._serialized_start=129
  _globals['_CREATEUSERRESPONSE']._serialized_end=182
  _globals['_GETUSERREQUEST']._serialized_start=184
  _globals['_GETUSERREQUEST']._serialized_end=212
  _globals['_GETUSERRESPONSE']._serialized_start=214
  _globals['_GETUSERRESPONSE']._serialized_end=264
  _globals['_LISTUSERSREQUEST']._serialized_start=266
  _globals['_LISTUSERSREQUEST']._serialized_end=284
  _globals['_LISTUSERSRESPONSE']._serialized_start=286
  _globals['_LISTUSERSRESPONSE']._serialized_end=339
  _globals['_DELETEUSERREQUEST']._serialized_start=341
  _globals['_DELETEUSERREQUEST']._serialized_end=372
  _globals['_DELETEUSERRESPONSE']._serialized_start=374
  _globals['_DELETEUSERRESPONSE']._serialized_end=411
  _globals['_USERSERVICE']._serialized_start=414
  _globals['_USERSERVICE']._serialized_end=731
# @@protoc_insertion_point(module_scope)
